version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose le service sur localhost:8080
    volumes:
      - ./WEB:/usr/share/nginx/html # Répertoire contenant le code PHP/HTML
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Configuration Nginx
    depends_on:
      - php

  php:
    build:
      context: ./WEB # Chemin vers le Dockerfile PHP
    container_name: php
    volumes:
      - ./WEB:/usr/share/nginx/html # Répertoire partagé avec Nginx
    depends_on:
      - db

  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432" # Expose le port PostgreSQL
    environment:
      POSTGRES_USER: admin # Nom d'utilisateur
      POSTGRES_PASSWORD: password # Mot de passe
      POSTGRES_DB: dashboard_db # Base de données par défaut
    volumes:
      - timescale-data:/var/lib/postgresql/data # Données persistantes
      - ./BD/script.sql:/docker-entrypoint-initdb.d/script.sql:ro # Script SQL à exécuter
volumes:
  timescale-data: