services:
  web:
    build:
      context: ./WEB # Chemin vers le Dockerfile Nginx
    container_name: nginx
    ports:
      - "8080:80" # Mapper le port 80 du conteneur sur le port 8080 de l'hôte
    volumes:
      - ./WEB/index.html:/usr/share/nginx/html/index.html:ro

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboard_db
    volumes:
      - timescale-data:/var/lib/postgresql/data

volumes:
  timescale-data:
